spring:
  datasource:
    url: jdbc:postgresql://db:5432/event_aggregator
    username: admin
    password: toor
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true


  data:
    redis:
      host: redis
      port: 6379

management:
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    root: INFO
    com.rubdev: DEBUG

app:
  provider:
    url: ${PROVIDER_URL:http://localhost:9090/api/events}
  cache:
    ttl-minutes: 20
    lock-timeout-seconds: 5
    key-prefix: events